from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor

def create_presentation(output_file="Credential_Audit_Presentation.pptx"):
    prs = Presentation()

    # Helper to create valid slide layouts
    # 0 = Title, 1 = Title+Content, etc.
    
    def add_slide(title_text, content_text_list):
        slide_layout = prs.slide_layouts[1] # Title and Content
        slide = prs.slides.add_slide(slide_layout)
        
        title = slide.shapes.title
        title.text = title_text
        
        body_shape = slide.shapes.placeholders[1]
        tf = body_shape.text_frame
        
        for i, item in enumerate(content_text_list):
            if i == 0:
                p = tf.paragraphs[0]
            else:
                p = tf.add_paragraph()
            p.text = item
            p.font.size = Pt(20)

    # 1. Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.shapes.placeholders[1]
    title.text = "Credential Audit Simulation Suite"
    subtitle.text = "Internship Project: Automated Ethical Security Assessment\n\nGenerated by Python Automation"

    # 2. Project Overview
    add_slide("1. Project Overview", [
        "Goal: Develop a practical toolkit for safe credential security assessment.",
        "Problem: Weak passwords remain a top cybersecurity vulnerability.",
        "Solution: A Python-based suite that simulates attacks on synthetic data.",
        "Key Features:",
        "  - Synthetic Data Generation (Linux/Windows)",
        "  - Pattern-Based Dictionary Attacks",
        "  - Risk Analytics (Entropy & Time-to-Crack)"
    ])

    # 3. Architecture
    add_slide("2. Architecture & Workflow", [
        "Step 1: Input & Mock Data (Generators)",
        "Step 2: Dictionary Mutation (Attack Engine)",
        "Step 3: Hash Identification (Utils)",
        "Step 4: Brute-Force Simulation (Engine)",
        "Step 5: Policy & Risk Analysis (Metrics)",
        "Step 6: Final Reporting (Markdown Report)"
    ])

    # 4. Technical Implementation
    add_slide("3. Technical Highlights", [
        "Language: Python 3.x",
        "Safety Core: Strictly isolated mock data. No interaction with real OS files.",
        "Algorithms Simulated:",
        "  - SHA-512 (Linux Shadow)",
        "  - NTLM/MD4 (Windows SAM)",
        "Advanced Logic: Leet-speak mutations (admin -> 4dm1n) and Entropy calculation."
    ])

    # 5. Results & Findings
    add_slide("4. Simulation Results", [
        "Benchmarks verified against test dataset (100% Success Rate).",
        "Identified 'Weak' passwords (<28 bits entropy) instantly.",
        "Calculated time-to-crack for 'Moderate' passwords (e.g., 4 days for 'summer2025').",
        "Demonstrated failures in standard length-only compliance policies."
    ])

    # 6. Conclusion
    add_slide("5. Conclusion & Recommendations", [
        "The simulation proves that standard dictionary attacks are highly effective against common patterns.",
        "Blue Team Recommendations:",
        "  1. Enforce MFA (Multi-Factor Authentication).",
        "  2. Increase Hashing Cost/Iterations.",
        "  3. Blacklist common dictionary words.",
        "Deliverables Completed: Codebase, Report, and Workflow Documentation."
    ])

    prs.save(output_file)
    print(f"[+] Presentation saved: {output_file}")

if __name__ == "__main__":
    create_presentation()
