import datetime

class ReportGenerator:
    def __init__(self):
        self.timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
    def _generate_flowchart(self):
        return """
```mermaid
graph TD
    A[Attacker] -->|Generates Wordlist| B(Dictionary Attack Engine)
    C[Mock Credential Store] -->|Extracts Hashes| B
    B -->|Hashes Guesses| D{Match Found?}
    D -- Yes --> E[Credential Compromised]
    D -- No --> F[Safe Next Iteration]
    E -->|Analyze| G[Audit Report]
```
"""

    def _get_recommendations(self, vulnerability_type):
        recs = {
            "Weak Password": [
                "Enforce minimum length of 12 characters.",
                "Implement MFA (Multi-Factor Authentication) to mitigation credential theft.",
                "Check new passwords against a 'banned list' of common terms."
            ],
            "Fast Check Time": [
                "Increase hashing iterations (e.g., use Argon2id with high cost).",
                "Ensure unique salts are at least 16 bytes for every user."
            ]
        }
        return recs.get(vulnerability_type, [])

    def generate_markdown_report(self, results, filename="Security_Audit_Report.md"):
        with open(filename, "w") as f:
            # Header
            f.write(f"# Internal Security Audit Simulation Report\n")
            f.write(f"**Date**: {self.timestamp}\n")
            f.write(f"**Scope**: Synthetic Credential Resilience Benchmark\n\n")
            
            # Executive Summary
            f.write("## 1. Executive Summary\n")
            f.write("This simulation benchmarked the resilience of user credentials against standard dictionary and pattern-based attacks. ")
            f.write(f"The audit tested {len(results)} mock identities and successfully demonstrated compromise pathways for heavily mutated passwords.\n\n")
            
            # Architecture
            f.write("## 2. Attack Simulation Architecture\n")
            f.write("The following diagram illustrates the simulated data flow used to benchmark excessive risk:\n")
            f.write(self._generate_flowchart())
            f.write("\n")
            
            # Technical Findings
            f.write("## 3. Technical Findings & Risk Analysis\n")
            f.write("| User Identity | Password Found | Entropy (Bits) | Est. Crack Time (GPU) | Risk Level |\n")
            f.write("|---|---|---|---|---|\n")
            
            from src.analytics.metrics import calculate_entropy, estimate_crack_time, evaluate_strength
            
            weak_count = 0
            for res in results:
                pw = res['password']
                ent = calculate_entropy(pw)
                strength = evaluate_strength(ent)
                time_est = estimate_crack_time(ent)
                
                if strength in ["Weak", "Very Weak"]:
                    weak_count += 1
                
                f.write(f"| {res['user']} | `{pw}` | {ent} | {time_est} | **{strength}** |\n")
            
            f.write("\n")
            
            # Recommendations
            f.write("## 4. Blue Team Defense Recommendations\n")
            f.write(f"**Critical Issue**: {weak_count} identities used passwords classified as 'Weak' or 'Very Weak'.\n\n")
            
            f.write("### Immediate Actions:\n")
            for rec in self._get_recommendations("Weak Password"):
                f.write(f"- [ ] {rec}\n")
                
            f.write("\n### Long-Term Strategy:\n")
            for rec in self._get_recommendations("Fast Check Time"):
                f.write(f"- [ ] {rec}\n")
                
            f.write("\n---\n*Generated by Python Credential Audit Suite - Educational Use Only*")
            
        print(f"[+] Report generated successfully: {filename}")

if __name__ == "__main__":
    # Test stub
    rep = ReportGenerator()
    rep.generate_markdown_report([], "test_report.md")
